# Generated by Django 4.1.1 on 2022-10-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='rentedBooks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
