# Generated by Django 4.1.1 on 2022-10-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_personaddress_rentedbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaddress',
            old_name='rentedBooks',
            new_name='rentedBook',
        ),
    ]
