# Generated by Django 4.1.1 on 2022-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_rentedbooks_personaddress_rentedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaddress',
            name='rentedBook',
        ),
        migrations.AddField(
            model_name='client',
            name='rentedBook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
